### PR TITLE
Updated Readme and other mods for map links and version

### PR DESCRIPTION
**Pull request by roydeanjr**
I updated the readme.md and added map link icons. Also updated the version to 2.0.0.
This PR actually wishes to merge with version2 rather than the master.

### CODE REVIEW

**Comment by roydeanjr** [comment]
Sam's suggestion on name change is to retire the old extension and create a new on with the new name. What ever is easier or if you wish me to go make the name change throughout, I can do that.

**Comment by ryanmitchell** [comment]
I would keep the same name. It’s something people search for and it still serves the role of a kitchen display.

**Comment by roydeanjr** [comment]
Conditional links looks good. I do not see the icons on the pickup orders I have in my list.

**Review by roydeanjr — COMMENTED** [review]
Looks good with one exception:
Buttons appear on the view that enables touch capability to move an order to a new status if your selection.

Not sure what "if your selection" at the end of this sentence. Could just drop that phrase unless "if" should be "in". 

Otherwise, let it rip.

**Comment by ryanmitchell** [comment]
Should have been an of, good spot :)

**Pull request merged**
