### PR TITLE
Added Date Time options

### PR DESCRIPTION
**Pull request by roydeanjr**
Added Date Time options to Cards tab selections

### CODE REVIEW

**Comment by ryanmitchell** [comment]
date would need added to array of orders in the Summary.php controller?
It should be formatted as follows: `$dateVariable->format(lang('system::lang.php.date_format'))`

**Comment by roydeanjr** [comment]
You are correct! I did forget about that modification I had done. My modification was this:
`$order->order_date = substr($order->order_date, 0, 10);` Is that modification ok? It works on my installation.

**Comment by ryanmitchell** [comment]
Yep thats what I mean 
👍

**Comment by ryanmitchell** [comment]
Pushed a couple of changes - let me know if it works ok for you.

**Comment by ryanmitchell** [comment]
Good spot!

**Comment by roydeanjr** [comment]
OMG! I was getting confused! I see you got the right code in line 214. I almost did a PR to put lines 127-128 back in and then thought about checking with your files before I did that.

You got everything in that needs to be there. Thank you! I am deleting all the branches and commits that I have in my profile. Will only pull when something needs to be changed.

**Pull request merged**
