### PR TITLE
Adding payment code to KD

### LINKED ISSUE #15: Add Toggle: Show payment code
Per discussion points in #12

### PR DESCRIPTION
**Pull request by BreakSecurity**
Here to you my first pull request. Fix #15

### CODE REVIEW

**Comment by BreakSecurity** [comment]
#15 Add this feature

**Comment by ryanmitchell** [comment]
Well done! 

My only change would be to add them as new line options rather than replacing the existing ones.

Could you change that please?

**Comment by BreakSecurity** [comment]
Done let me know ;)

**Comment by ryanmitchell** [comment]
Updated with what I had intended.
If you're happy I'll merge

**Comment by BreakSecurity** [comment]
I would like to have the possibility to have both telephone and payment code because what is great about KD to me is the general overview it provides across several orders. Maybe we can take only 3 char of payment code and add it after total. STRIPE -> STR and so on. What do you think?

**Comment by ryanmitchell** [comment]
Address is usually long which is why its by itself on a line, adding phone to it is a bad idea in my opinion.
I personally dont see the value in payment code at all as its on all the order receipts we print out.

**Comment by BreakSecurity** [comment]
And if we add only the 3 chars payment code to the first line without removing anything (time phone total and code)? Or we can just leave in anew line that is off by default

**Comment by ryanmitchell** [comment]
Name can be quite long too.
You can add it as options and I'll accept it, just dont remove or modify any of the existing options.

**Comment by BreakSecurity** [comment]
There is a way to return to c5e1b6e when it was in a new line? Or I should redo manually and commit?

**Comment by ryanmitchell** [comment]
I don't want another line - 3 lines is the right amount of real estate on screen.

**Comment by ryanmitchell** [comment]
Can you not push until you are done? I get a notification on every push so have about 15 emails so far :)

**Comment by BreakSecurity** [comment]
I am really sorry I am trying to revert back a delete action. Still new to git and I dunno how to push only to my git and not in the pull req. I think I will close this and redo from zero

**Pull request closed without merging**
