### PR TITLE
Added the possibility to choose between maps, bing, both or none

### PR DESCRIPTION
**Pull request by BreakSecurity**
More flexibility added

Bing is not working for me @roydeanjr maybe you can look the way it generate the link.

### CODE REVIEW

**Comment by BreakSecurity** [comment]
Maybe I can move bing and maps links to two variables in summary php to avoid repetition, let me know if for you is good like this

**Comment by roydeanjr** [comment]
For me, it is probably good. I do not have delivery orders so my add of delivery and map links was thinking others would have delivery orders and the convenience of being able to just click the link while looking at the order would be kinda nice. If it works for you, it is good for me; at least for my current use cases.

Thank you for asking......

**Comment by ryanmitchell** [comment]
Pushed a few changes - if your happy let me know and I'll merge

**Comment by BreakSecurity** [comment]
You can marge ;)

**Comment by BreakSecurity** [comment]
Sorry I just noticed that bing only have destination setted and not starting point. I was fooled by destination

**Comment by ryanmitchell** [comment]
You can get that form the current device location, dont think its needed.

**Pull request merged**
