### PR TITLE
Fix for beta > 26 ASAP related

### PR DESCRIPTION
**Pull request by BreakSecurity**
ASAP option adjustments

### CODE REVIEW

**Comment by BreakSecurity** [comment]
immagine
instead of

immagine

**Comment by ryanmitchell** [comment]
Like the idea but ‘Order time is ASAP’ is very long. Is there a shorter string we can use?

**Comment by BreakSecurity** [comment]
Let me check

**Comment by ryanmitchell** [comment]
If not we should roll our own - ‘ ASAP’ is enough.

**Comment by BreakSecurity** [comment]
Found this one in local ext.

**Pull request merged**
